### ISSUE TITLE
Am I Being Daft?

### ISSUE THREAD

**Issue by dewmguy** [Guerra24/firefox-discord#1]
I am not finding an ".xpi" file to install.

**Comment by Guerra24** [comment]
In the releases page, above the AppImage and exe. [This file](https://github.com/Guerra24/firefox-discord/releases/download/v1.0.1_1/discord_rich_presence-1.0.1-fx.xpi)

**Comment by dewmguy** [comment]
Thanks, I'm dumb 😄
